version: '3'
services:
  # influxdb to accept incoming stats measurements
  influxdb:
    image: influxdb:latest
    expose:
      - 8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_WRITE_USER=${INFLUXDB_AUTH_USER}
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_AUTH_PASSWORD}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.scope: "julia_grafana"

  # grafana to display them beautifully
  grafana:
    image: grafana/grafana:latest
    expose:
      - 3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SERVER_ROOT_URL=https://${FQDN}
      - GF_SERVER_DOMAIN=${FQDN}
      - GF_SERVER_PROTOCOL=http
      # When auto-logging in via GitHub, this is the only way to get initial admin
      - GF_SECURITY_ADMIN_USER=staticfloat
      - GF_AUTH_GITHUB_ENABLED=true
      - GF_AUTH_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GF_AUTH_GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS=JuliaLang JuliaLabs
      - GF_AUTH_GITHUB_ALLOW_SIGN_UP=true
      - GF_AUTH_OAUTH_AUTO_LOGIN=true
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.scope: "julia_grafana"

  # nginx TLS termination/frontend
  frontend:
    image: staticfloat/nginx-certbot
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: staticfloat@gmail.com
      FQDN: ${FQDN}
      ENVSUBST_VARS: FQDN
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana
    volumes:
      - ./${FQDN}.conf:/etc/nginx/user.conf.d/${FQDN}.conf
      # Keep SSL certificates permanently
      - letsencrypt:/etc/letsencrypt
    labels:
      com.centurylinklabs.watchtower.scope: "julia_grafana"

  # Watchtower to auto-update
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --scope julia_grafana
volumes:
  influxdb-storage:
  grafana-storage:
  letsencrypt:
